version: '3.8'
services:
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8085:8080" # Map port 8085 ngoài máy thật vào 8080 của container
    environment:
      - KAFKA_CLUSTERS_0_NAME=UET-BigData-Cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=master14:9092
    extra_hosts:
      - "master14:10.148.0.2"
      - "worker141:10.148.0.3"
      - "worker142:10.148.0.4"
    restart: always